In [22]:
# Import pandas library to read and handle dataset files such as CSV

import pandas as pd

In [23]:
# Load the dataset from the CSV file into a dataframe

dataset=pd.read_csv("Salary_Data.csv")

In [24]:
# Display the dataset to understand its structure
#YearsExperience → input feature
#Salary → output value we want to predict.

dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [25]:
# Extract the independent variable (input feature)
#YearsExperience = independent variable (X)

independent=dataset[["YearsExperience"]]
independent

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [26]:
# Extract the dependent variable (target/output)
#Salary is the target variable (Y) that the model will learn to predict.

dependent=dataset[["Salary"]]
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [27]:
# Split dataset into training and testing sets
# 70% of data used for training and 30% used for testing
#test_size = 0.30 → 30% data reserved for testing.
#random_state = 0 → ensures the same split every time the code runs.

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0)

In [28]:
# Import Linear Regression algorithm

from sklearn.linear_model import LinearRegression

# Create the regression model
#Salary=w(YearsExperience)+b

regressor=LinearRegression()

# Train the model using the training dataset

regressor.fit(X_train,Y_train)

LinearRegression()

In [29]:
#Retrieve the slope (weight) learned by the model
#Every 1 year of experience increases salary by about 9360

weight=regressor.coef_
weight

array([[9360.26128619]])

In [30]:
# Retrieve the intercept (bias)
#Intercept is the predicted salary when experience = 0.

bias=regressor.intercept_
bias

array([26777.3913412])

In [31]:
# Predict salary values for the test dataset

Y_pred=regressor.predict(X_test)

In [32]:
# Import evaluation metric

from sklearn.metrics import r2_score

# Calculate R² score to measure model accuracy

r_score=r2_score(Y_test,Y_pred)

In [33]:
r_score

0.9740993407213511

In [45]:
# Import pickle library to save and load trained machine learning models

import pickle

# Define the filename where the trained model will be stored
#.sav is just a common extension used for saved models

filename="finalized_model_linear.sav"

In [48]:
# Save the trained regression model into a file using pickle

pickle.dump(regressor,open(filename,'wb'))

#This step stores the trained model on disk.
#pickle.dump() saves an object
#regressor trained ML model
#open(filename,'wb') open file in write binary mode

In [49]:
# Load the saved model from the file
#This step retrieves the saved model from the file so it can be used again.
#pickle.load() loads serialized object
#rb read binary
#loaded_model loaded_model

loaded_model=pickle.load(open("finalized_model_linear.sav",'rb'))

# Predict salary for a given years of experience (10 years)
#Salary=9360.26×Experience+26777.39

result=loaded_model.predict([[10]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [51]:
# Display the predicted salary

result

array([[120380.00420313]])